highlighter: pygments
github: [Repository metadata]
encoding: utf-8
exclude: ["Gemfile", "Gemfile.lock", "README.md", 'sass', 'watch.sh', 'style.scss'] # files to exclude

# Site settings
url: "http://localhost:4000"

# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Taiwan
tagline:          My life in Taiwan
url:              http://doversten.se
paginate:         1
baseurl:          /
author:
  name:           Martin Doversten
  url:            https://twitter.com/doversten
  email:          martin@doversten.se

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole